### ISSUE TITLE
Does not work on Angular 7 and ngxFormly > 5

### ISSUE THREAD

**Issue by nkovacic** [franzeal/ngx-formly-tabs#2]
No tabs are shown because TabsetService is undefined in TabComponent. 

Example: [https://codesandbox.io/s/angular-7-template-w28yv?fontsize=14](https://codesandbox.io/s/angular-7-template-w28yv?fontsize=14)

**Comment by ilijev07** [comment]
Like a workaround for it can be made with providing TabsetService in the module directly instead of component, I tried and it works fine.

**Comment by franzeal** [comment]
I've published version 5.0.0 intended to address this issue.  Limited testing seemed to indicate the prescribed workaround for the [issue](https://github.com/ngx-formly/ngx-formly/issues/1622) in formly v5 doesn't work in prior formly versions (not without more workarounds).

The impact of the workaround is a switch from a wrapper to a type, though only for the tabset; doing it to both tabset and tab would also suffer from a broken component-level injector.

Updated usage is demonstrated here:
https://github.com/franzeal/ngx-formly-tabs/tree/v5

**Comment by franzeal** [comment]
I've published version 5.1.0 to target the newly released formly 5.2.0 which enables some degree of component-level injectors, thus the tab can be used as a type.  The tab wrapper will also remain an option.  The demo's been updated to use this latest version.
