### ISSUE TITLE
creating for Material Tabs, based on the library

### ISSUE THREAD

**Issue by GlauberF** [franzeal/ngx-formly-tabs#5]
I'm creating something similar for Mat tabs (Material), but I'm not able to keep it working 100%.

The first TAB, does not appear.
Stackblitz: https://stackblitz.com/edit/mat-tabs-vimbo-form

who can comment here to help me, I am grateful.

**Comment by franzeal** [comment]
I think the key difference here is in the `TabsetComponent`.  I originally set out to use ng-bootstrap's tab implementation, but ran into limitations that led to the approach you see in ngx-formly-tabs.  Below are links to those original issues that led me to this solution.

https://github.com/ngx-formly/ngx-formly/issues/263
https://github.com/ng-bootstrap/ng-bootstrap/issues/1069

Maybe I had tunnel vision at the time.  Hard to say what limitations may crop up without really trying to use this, but you may be able to accomplish as much with the field type alone:
https://stackblitz.com/edit/mat-tabs-vimbo-form-pf1pms

**Comment by GlauberF** [comment]
Thanks @franzeal , helped me a lot
