### ISSUE TITLE
fieldGroupClassName not supported?

### ISSUE THREAD

**Issue by koolkunz** [franzeal/ngx-formly-tabs#8]
Hi,

is the fieldGroupClassName tag not supported or am I missing something?

**Comment by franzeal** [comment]
You weren't missing anything.  v5.3.0 should have it for you.

**Comment by koolkunz** [comment]
Wow, thank you for adding it so quickly!

I have one small doubt regarding this though:

https://stackblitz.com/edit/ngx-formly-tabs-eyci9e?file=src/app/app.component.ts

if you look at this code and see the difference between the two tabs, one I created using type : "tab" and the other using wrappers: ["tab"], and you can see how differently they are behaving (seperate lines in case of using type and same line in case of using wrapper). Is this the expected functionality?

**Comment by franzeal** [comment]
It's expected.  It makes the most sense to use the type for both the tabset (required) and tabs.  That there's still a wrapper available for tabs is a relic, but I do like their flexibility.  If needed, I can add a recognized template option that will allow a class name to be applied to the wrapper element.

**Comment by koolkunz** [comment]
But I want it to work like it is working with wrappers, I want 2 or 3 input fields in one row. Any way that can be achieved using type instead of wrapper (although it doesnt matter that much, I dont mind using wrapper).

**Comment by franzeal** [comment]
The behavior you see when a field combines the `type` and `fieldGroup` as the tabset and tab do is formly's, which is part of what separates the type versus wrapper approach.

In this case, I'd suggest nesting field groups within the tab type for each row.  I can dig into this later / this weekend if it's not working as expected.

**Comment by koolkunz** [comment]
nesting field groups within type tab is working, thanks again for all your help!
